name: TicketTestCI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup
        run: |
          git clone https://github.com/junegunn/vader.vim.git
          git checkout -b testing_branch
          # required for testing GetAllBranchNames
          git branch --force test_1
          git branch --force feature/test_2 

      - name: Run Tests
        run: |
          vim -Nu <(cat << VIMRC
          filetype off
          set rtp+=vader.vim
          set rtp+=.
          set rtp+=after
          filetype plugin indent on
          syntax enable
          VIMRC) -c 'Vader! test/*.vader' > /dev/null
